name: fastapi-stack

services:
  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped

    environment:
      POSTGRES_USER: reaper
      POSTGRES_PASSWORD: junaid
      POSTGRES_DB: data

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reaper -d data"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - app-network

  backend:
    image: fastapi-backend:1
    container_name: backend
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy

    networks:
      - app-network

  frontend:
    image: fastapi-frontend:2
    container_name: frontend
    restart: unless-stopped

    ports:
      - "3000:3000"

    depends_on:
      - backend

    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
